services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    ports:
      - "7777:8000"
    networks:
      - myNetwork
    env_file:
      - .env
  
  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  myNetwork:
    external: true

#services:
#  postgres_dwh:
#    image: postgres:15
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: booking
#    restart: always
#    ports:
#      - "5432:5432"
#
#  redis:
#    image: redis:latest
#    container_name: redis_container
#    environment:
#      - REDIS_PASSWORD=password
#      - REDIS_USER=username
#      - REDIS_USER_PASSWORD=password_username
#    ports:
#      - "6380:6379"
#    volumes:
#      - ./redisdata:/data
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    command: >
#      sh -c '
#        mkdir -p /usr/local/etc/redis &&
#        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
#        echo "requirepass password" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
#        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
#        echo "user username on >password_username ~* +@all" >> /usr/local/etc/redis/users.acl &&
#        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
#      '
#    healthcheck:
#      test: ["CMD", "redis-cli", "-a", "password", "ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#    tty: true
#    stdin_open: true
