"""add table Users

Revision ID: bf6c8fa87bb2
Revises: 3341d40f0518
Create Date: 2026-03-24 13:57:28.486793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bf6c8fa87bb2"
down_revision: Union[str, Sequence[str], None] = "3341d40f0518"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
