"""rename col

Revision ID: 0c95676bc333
Revises: bf6c8fa87bb2
Create Date: 2026-03-24 15:46:57.146268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0c95676bc333"
down_revision: Union[str, Sequence[str], None] = "bf6c8fa87bb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=200), nullable=False)
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
